# Generated by Django 4.2.9 on 2024-01-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_alter_order_course_alter_order_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='course',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
