# Generated by Django 4.2.9 on 2024-01-27 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_alter_order_course_alter_order_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.course'),
        ),
        migrations.AlterField(
            model_name='order',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.department'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
