# Generated by Django 4.2.9 on 2024-01-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_alter_order_age_alter_order_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='deptid',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='course',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
