# Generated by Django 4.2.9 on 2024-01-27 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_alter_course_deptid_alter_order_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='deptid',
            new_name='dept',
        ),
    ]
