# Generated by Django 4.2.9 on 2024-01-27 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_rename_deptid_course_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.department'),
        ),
        migrations.AlterField(
            model_name='order',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.course'),
        ),
        migrations.AlterField(
            model_name='order',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.department'),
        ),
    ]
